title: AÉDIROUM
baseurl: https://aediroum.ca
theme: aediroum

# Menu
menu:
  main:
    - name: Événements
      identifier: evenements
      weight: 4
    - name: Documents
      identifier: documents
      weight: 5
    - name: Charte
      url: /documents/charte
      parent: documents
      weight: 1
    - name: Vie étudiante
      url: /documents/coussin
      parent: documents
      weight: 2
    - name: Affiliation à la FAÉCUM
      url: /documents/faecum
      parent: documents
      weight: 3
    - name: Cahier de positions
      url: /documents/positions
      parent: documents
      weight: 4
    - name: Code de vie
      url: /documents/codedevie
      parent: documents
      weight: 5

# Output formats
outputs:
  section:
    - HTML
    - RSS
    - Calendar

# Language
defaultContentLanguage: fr
languageCode: fr

# Markdown
markup:
  goldmark:
    renderer:
      unsafe: true

# Crawling
enableRobotsTXT: true
disableHugoGeneratorInject: true

# Miscellaneous
metaDataFormat: yaml
buildFuture: true
enableGitInfo: true
pagination:
  pagerSize: 5
