title: AÉDIROUM
baseurl: https://aediroum.ca
theme: aediroum

# Menu
menu:
  main:
    - Name: Événements
      Identifier: evenements
      Weight: 4
    - Name: Documents
      Identifier: documents
      Weight: 5

# Output formats
outputs:
  section:
    - HTML
    - RSS
    - Calendar

# Language
defaultContentLanguage: fr
languageCode: fr

# Markdown
markup:
  goldmark:
    renderer:
      unsafe: true

# Crawling
enableRobotsTXT: true
disableHugoGeneratorInject: true

# Miscellaneous
metaDataFormat: yaml
buildFuture: true
enableGitInfo: true
paginate: 5
